name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build --prod

    - name: Print VERCEL_TOKEN
      run: echo "VERCEL_TOKEN is $VERCEL_TOKEN"
    
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

    
